{ colors, font, ... }: ''

  font:
    normal:
      family: "${font.sans.family}"
      style: "${font.sans.weight}"

    bold:
      family: "${font.sans.family}"
      style: "Bold"

    italic:
      family: "${font.sans.family}"
      style: "${font.sans.weight} Italic"

    bold_italics:
      family: "${font.sans.family}"
      style: "${font.sans.weight} Italic"

    size: ${toString (font.mono.size)}

    offset:
      x: 0
      y: 0

    glyph_offset:
      x: 0
      y: 0

    use_thin_strokes: true

  colors:
    primary:
      foreground: "${colors.types.fg}"
      background: "${colors.types.bg}"

    cursor:
      text: "${colors.types.bg}"
      cursor: "${colors.yellow}"

    selection:
      text: "${colors.types.bg}"
      background: "${colors.types.highlight}"

    normal:
      black: "${colors.black}"
      red: "${colors.red}"
      green: "${colors.green}"
      yellow: "${colors.yellow}"
      blue: "${colors.blue}"
      magenta: "${colors.magenta}"
      cyan: "${colors.cyan}"
      white: "${colors.white}"

    bright:
      black: "${colors.brightBlack}"
      red: "${colors.brightRed}"
      green: "${colors.brightGreen}"
      yellow: "${colors.brightYellow}"
      blue: "${colors.brightBlue}"
      magenta: "${colors.brightMagenta}"
      cyan: "${colors.brightCyan}"
      white: "${colors.brightWhite}"
''
